### ISSUE TITLE
routing example new joined node doesn't get its Routing table populated

### ISSUE THREAD

**Issue by maqi** [dirvine/routing#185]
this video shows the issue : 
https://maidsafe.slack.com/files/qi.ma/F04M16EC6/routing_example_bootstrap_3_nodes.mp4

it is probably due to the find_group msg doesn't get properly fired and handled

**Comment by chandraprakash** [comment]
This should include a test to confirm this behaviour.

**Comment by maqi** [comment]
with the updates in crust lib, this issue get resolved.

**Comment by chandraprakash** [comment]
I will keep this open until we have a test for the same.

**Comment by maqi** [comment]
sorry, I had a wrong impression of what this issue is about.
the issue is still there and need some work on routing to resolve

**Comment by rossmuir** [comment]
Local LAN testing of routing example on 11 different machines - running the example with `-n` 
All nodes on all platforms connected and have at least 1 node in their RT
Most nodes only have a `RT size:1` the largest was `RT size:8`

**Comment by mmoadeli** [comment]
As initial steps for doing task below are to be done
1- Remove public pmid from BootstrapId Response message
2- Stop sending bootstrap id request from both sides of the communication
3- Add bootstrap related info only if none already is there
4- change signature of the send_bootstrap_response_id as mentioned in  #188
