### ISSUE TITLE
Cache handling not implemented 

### ISSUE THREAD

**Issue by chandraprakash** [dirvine/routing#190]
Implement handle_cache_get/handle_cache_put Interfaces in the example code. The implementation should be similar to handle_get / handle_put implementation. They should use the same container (Stats) used by handle_get / handle_put. This will allow routing caching to work. So any get request can be addressed by the intermediate nodes on the way to target group if they have the data in the cache. And any data which is cacheable, then it is cached on all hops till the target group.

**Comment by maqi** [comment]
https://github.com/dirvine/routing/pull/199

**Comment by chandraprakash** [comment]
Fix looks good. Thanks Qi
