### ISSUE TITLE
authority check on handle put

### ISSUE THREAD

**Issue by chandraprakash** [dirvine/routing#194]
In implementation of handle_put interface, only perform the put operation if the  our_authority is NAE manager. put operation refers to adding data in the stats container. In case our_authority != NAE manager, it should silently drop the request, this means returning success from the method. Returning success means terminating the message flow.

**Comment by maqi** [comment]
this shall be done on vault level.
routing supposed to only know the role or routing or non-routing

**Comment by chandraprakash** [comment]
Routing guarantees validated authorities being passed to upper layers. So, thinking Routing again as a DHT. What we want to say in the example is that, we store data into the group of Nodes closed to a given address only if the authority confirmed by routing is  NAE manager. ie They know they are this type of group as they are close to the address that equals the name of the network addressable element.

**Comment by maqi** [comment]
to make the example work properly, it requires beacon and sentinel working properly so the changed code can be verified.
and just change it in routing will blocking the verification of changes to resolve other issues.
So prefer to postpone this task till beacon and sentinel starts working properly.

**Comment by chandraprakash** [comment]
beacon works now. Even if sentinel is not enabled, I will say go ahead and do the required implementation for this issue. This will at least make example program complete.

**Comment by maqi** [comment]
PR is here : https://github.com/dirvine/routing/pull/208
However just as I worried, the vault reporting : "returning as our_authority is ClientManager which is not supposed to handle_put"
and no data can be stored to network.
This might be a bug, or maybe not enough nodes get setup.

**Comment by chandraprakash** [comment]
routing_client::put() goes to client manager, so we need to Fwd it to NAE manager in this case.

**Comment by maqi** [comment]
the PR has been updated to include the forwarding logic.
this issue is now resolved.
