### ISSUE TITLE
Bootstrap should be a docopt option

### ISSUE THREAD

**Issue by chandraprakash** [dirvine/routing#195]
Bootstrap should be only called once and not be called repetitively for populating routing table. Allow this as optional and only once in the example. Have it as a command line arg (docopt) rather than an option on CLI. (-b bootstrap_endpoint).

**Comment by maqi** [comment]
it is a line arg already, and -b bootstrap_endpoint is for docopt

currently allowing to be called repetitively just because beacon doesn't work

**Comment by chandraprakash** [comment]
I can't see a separate -b option in here. We will not need -b option all the time, so it should be an optional argument. We don't need this option if beacon gets us the bootstrap information.
This will allow us to use the example on droplets(beacon doesn't work here). So it should be 
       routing -o 
       routing -n // routing_node
       routing -c  // client_node
      routing -b <endpoint> bootstrap to the specified endpoint

Current options :
$ cargo run --example routing -- -h
     Running `target/debug/examples/routing -h`
Usage: routing -h
       routing -o
       routing -v <endpoint>
       routing -c <endpoint>

Options:
    -h, --help       Display the help message
    -o, --origin     Startup the first testing node
    -c, --client     Node started as client, bootstrap to the specified endpoint
    -v, --vault      Node started as vault, bootstrap to the specified endpoint

**Comment by Fraser999** [comment]
Do we need the `-o` option?  If the first node can't find any peers via crust, it'll know it's the first node.  Also, should we default to using client mode (i.e. take away the `-c` option) since that will generally be the more interesting for users to run (since I assume they'll then be able to put/get data)?

Ideally, I think we should be aiming for just running the example with no args.  I guess we'll often need a bootstrap arg if there aren't any other nodes on our subnet, but apart from that... ?

**Comment by chandraprakash** [comment]
I agree Fraser, its simpler for users.
So, we don't use -o option at all.
If the first node can't find any peers via crust, it'll know it's the first node. So, routing::bootstrap() method of the first node will fail and in the example code we can put a message on terminal saying this is the first node.
So the option set will be : 

routing -n // routing_node
routing // client_node (defaulted to client, as its easy for users to run clients and do GET/PUT)
routing [-b <peer>]  // optional bootstrap to the specified endpoint

**Comment by Fraser999** [comment]
The closest to crust's example docopt stuff would be something like:

```
Usage:
  routing [<peer>...]
  routing --node [<peer>...]
  routing --help

The node will try and bootstrap off one of the peers if any are provided.  If
no connections can be made, Crust's discovery protocol will be used.

Options:
  -n, --node  Run as a RoutingNode rather than a RoutingClient.
  -h, --help  Display this help message.
```

**Comment by chandraprakash** [comment]
@maqi  plz consider Fraser's comment as the final requirement. 
Also, I have noticed in your previous PR that you were overriding default bootstrapping methods. 
We need to pass None to bootstrap method. I have commented on you PR 
https://github.com/dirvine/routing/pull/184/files

**Comment by maqi** [comment]
maybe I misunderstood crust::beacon, or maybe there is bug in routing, however I don't see routing nodes can discover each other automatically.

**Comment by maqi** [comment]
https://github.com/dirvine/routing/pull/209

**Comment by maqi** [comment]
the above PR has been updated to include the usage of beacon.
However, though the ConnectionManager has called seekpeers method trying to discover live nodes when start up the second node,
the first node can not be properly spotted (seekpeers returns empty list).
Seems like a bug somewhere in seekpeers

**Comment by chandraprakash** [comment]
Thanks Qi for looking into it. Can you create an  issue with this one. This task should care about using the api correctly. So the scope of this task is covered.

**Comment by maqi** [comment]
https://github.com/dirvine/routing/issues/213

**Comment by Viv-Rajkumar** [comment]
PR #217 builds up on PR #215
