### ISSUE TITLE
Routing example client should accept key, value as string for GET/PUT

### ISSUE THREAD

**Issue by chandraprakash** [dirvine/routing#196]
Routing example client should accept key, value as string for GET/PUT. The example should have an option to Put data as name value pair. example Put(“apple”, “abcd”). The example should internally hash key to get the name of the data element(Sendable::name). The value should be sent as it is.

**Comment by maqi** [comment]
I don't see the point to do that.
The purpose of routing example to evaluate the connections and routing table, not the datatype support, that shall be vault example's (testnet) job.

**Comment by chandraprakash** [comment]
Routing library is also a DHT, so it should allow users to store unrelated key value pairs.
The purpose of this example is also to show users how to routing library just as a DHT.
Refer TODO point - Routing Client accepting key, value as string for GET/PUT

**Comment by maqi** [comment]
https://github.com/dirvine/routing/pull/207

**Comment by chandraprakash** [comment]
Nice one ! thanks Qi
