### ISSUE TITLE
Unable to bootstrap second node using bootstrap option in CLI.

### ISSUE THREAD

**Issue by chandraprakash** [dirvine/routing#197]
Steps: start 1st and 2nd node using command :  cargo run --example routing -- -o
bootstrap 2nd node to 1st node  cli option : bootstrap 0.0.0.0:5483
error : Failed to bootstrap: Error { repr: Custom(Custom { kind: Other, error: StringError("No bootstrap node got connected") }) }

**Comment by maqi** [comment]
5483 will only get listened unless you modify the code, as pointed out in the shared video.
otherwise it will be a random port being picked up to listen.

using 5483 just because beacon is not working.

**Comment by chandraprakash** [comment]
okay, this will be fixed with beacon fix.

**Comment by maqi** [comment]
duplicated to Issue 185 : https://github.com/dirvine/routing/issues/185
suggested to close this issue
