### ISSUE TITLE
crust::ConnectionManager::seek_peers seems not working properly in routing example

### ISSUE THREAD

**Issue by maqi** [dirvine/routing#213]
This is a spin out issue from Issue 195 : https://github.com/dirvine/routing/issues/195
when start up nodes trying to utilise beacon : 
      starting first node : routing -n
      starting later on nodes : routing -n
      starting a client : routing

the second node and client can not discover the first node.
investigations shows that the return from crust::ConnectionManager::seek_peers method during the bootstrap is always empty list.

**Comment by chandraprakash** [comment]
This issue seems fixed after merging this pr 
https://github.com/dirvine/routing/pull/217
